Repository teamterning/Terning-Server-Kotlin, pull requests merged in 2025-06, with the labels that each got.

#82 [✨feat] 스크랩 추가 API 구현
  build.gradle.kts
  src/main/kotlin/com/terning/server/kotlin/application/scrap/ScrapRequest.kt
  src/main/kotlin/com/terning/server/kotlin/application/scrap/ScrapService.kt
  src/main/kotlin/com/terning/server/kotlin/application/temp
  src/main/kotlin/com/terning/server/kotlin/domain/auth/Auth.kt
  src/main/kotlin/com/terning/server/kotlin/domain/auth/AuthRepository.kt
  src/main/kotlin/com/terning/server/kotlin/domain/internshipAnnouncement/InternshipAnnouncement.kt
  src/main/kotlin/com/terning/server/kotlin/domain/internshipAnnouncement/InternshipAnnouncementRepository.kt
  src/main/kotlin/com/terning/server/kotlin/domain/scrap/ScrapRepository.kt
  src/main/kotlin/com/terning/server/kotlin/domain/scrap/exception/ScrapErrorCode.kt
  src/main/kotlin/com/terning/server/kotlin/domain/scrap/vo/Color.kt
  src/main/kotlin/com/terning/server/kotlin/domain/user/User.kt
  src/main/kotlin/com/terning/server/kotlin/domain/user/UserRepository.kt
  src/main/kotlin/com/terning/server/kotlin/domain/user/vo/UserName.kt
  src/main/kotlin/com/terning/server/kotlin/ui/api/ScrapController.kt
  src/main/resources/application-test.yml
  src/test/kotlin/com/terning/server/kotlin/application/scrap/ScrapServiceTest.kt
  src/test/kotlin/com/terning/server/kotlin/domain/user/UserTest.kt
  src/test/kotlin/com/terning/server/kotlin/ui/api/ScrapControllerTest.kt
Labels: ✨ feat, 🐋 장순 🐋, size/L

#94 [✨feat] 월간 캘린더(기본 뷰) API구현
  build.gradle.kts
  src/main/kotlin/com/terning/server/kotlin/application/scrap/ScrapRequest.kt
  src/main/kotlin/com/terning/server/kotlin/application/scrap/ScrapService.kt
  src/main/kotlin/com/terning/server/kotlin/application/scrap/dto/MonthlyScrapDeadlineResponse.kt
  src/main/kotlin/com/terning/server/kotlin/application/scrap/dto/ScrapRequest.kt
  src/main/kotlin/com/terning/server/kotlin/application/scrap/dto/ScrapUpdateRequest.kt
  src/main/kotlin/com/terning/server/kotlin/config/QuerydslConfig.kt
  src/main/kotlin/com/terning/server/kotlin/config/temp
  src/main/kotlin/com/terning/server/kotlin/domain/internshipAnnouncement/vo/Company.kt
  src/main/kotlin/com/terning/server/kotlin/domain/scrap/ScrapRepository.kt
  src/main/kotlin/com/terning/server/kotlin/domain/scrap/ScrapRepositoryCustom.kt
  src/main/kotlin/com/terning/server/kotlin/domain/scrap/ScrapRepositoryImpl.kt
  src/main/kotlin/com/terning/server/kotlin/domain/scrap/exception/ScrapErrorCode.kt
  src/main/kotlin/com/terning/server/kotlin/ui/api/ScrapController.kt
  src/test/kotlin/com/terning/server/kotlin/application/scrap/ScrapServiceTest.kt
  src/test/kotlin/com/terning/server/kotlin/ui/api/scrap/ScrapControllerTest.kt
Labels: ✨ feat, 🐋 장순 🐋, size/L

#96 [✨feat] 사용자 필터링 정보 API 구현
  src/main/kotlin/com/terning/server/kotlin/application/filter/FilterResponse.kt
  src/main/kotlin/com/terning/server/kotlin/application/filter/FilterService.kt
  src/main/kotlin/com/terning/server/kotlin/domain/filter/FilterRepository.kt
  src/main/kotlin/com/terning/server/kotlin/domain/filter/exception/FilterErrorCode.kt
  src/main/kotlin/com/terning/server/kotlin/ui/api/FilterController.kt
  src/test/kotlin/com/terning/server/kotlin/application/filter/FilterServiceTest.kt
  src/test/kotlin/com/terning/server/kotlin/ui/api/filter/FilterControllerTest.kt
Labels: ✨ feat, 🐬 유빈🐬, size/L

#99 [✨feat] 일간 캘린더 API구현
  src/main/kotlin/com/terning/server/kotlin/application/scrap/ScrapService.kt
  src/main/kotlin/com/terning/server/kotlin/application/scrap/dto/DetailedMonthlyScrapResponse.kt
  src/main/kotlin/com/terning/server/kotlin/domain/scrap/ScrapRepositoryCustom.kt
  src/main/kotlin/com/terning/server/kotlin/domain/scrap/ScrapRepositoryImpl.kt
  src/main/kotlin/com/terning/server/kotlin/ui/api/ScrapController.kt
  src/test/kotlin/com/terning/server/kotlin/application/scrap/ScrapServiceTest.kt
  src/test/kotlin/com/terning/server/kotlin/ui/api/scrap/ScrapControllerTest.kt
Labels: ✨ feat, 🐋 장순 🐋, size/L

#102 [✨feat] 딱 맞는 대학생 인턴 공고 API 구현
  src/main/kotlin/com/terning/server/kotlin/application/filter/FilterService.kt
  src/main/kotlin/com/terning/server/kotlin/application/internshipAnnouncement/InternshipAnnouncementService.kt
  src/main/kotlin/com/terning/server/kotlin/application/internshipAnnouncement/dto/HomeAnnouncementsResponse.kt
  src/main/kotlin/com/terning/server/kotlin/config/JpaAuditingConfiguration.kt
  src/main/kotlin/com/terning/server/kotlin/domain/filter/Filter.kt
  src/main/kotlin/com/terning/server/kotlin/domain/filter/FilterRepository.kt
  src/main/kotlin/com/terning/server/kotlin/domain/filter/FilterRepositoryCustom.kt
  src/main/kotlin/com/terning/server/kotlin/domain/filter/FilterRepositoryImpl.kt
  src/main/kotlin/com/terning/server/kotlin/domain/filter/exception/FilterErrorCode.kt
  src/main/kotlin/com/terning/server/kotlin/domain/filter/vo/FilterGrade.kt
  src/main/kotlin/com/terning/server/kotlin/domain/filter/vo/FilterMonth.kt
  src/main/kotlin/com/terning/server/kotlin/domain/filter/vo/FilterWorkingPeriod.kt
  src/main/kotlin/com/terning/server/kotlin/domain/filter/vo/FilterYear.kt
  src/main/kotlin/com/terning/server/kotlin/domain/internshipAnnouncement/InternshipAnnouncement.kt
  src/main/kotlin/com/terning/server/kotlin/domain/internshipAnnouncement/InternshipAnnouncementRepository.kt
  src/main/kotlin/com/terning/server/kotlin/domain/internshipAnnouncement/InternshipAnnouncementRepositoryCustom.kt
  src/main/kotlin/com/terning/server/kotlin/domain/internshipAnnouncement/InternshipAnnouncementRepositoryImpl.kt
  src/main/kotlin/com/terning/server/kotlin/domain/internshipAnnouncement/SortType.kt
  src/main/kotlin/com/terning/server/kotlin/domain/internshipAnnouncement/exception/InternshipAnnouncementErrorCode.kt
  src/main/kotlin/com/terning/server/kotlin/domain/internshipAnnouncement/vo/InternshipAnnouncementScrapCount.kt
  src/main/kotlin/com/terning/server/kotlin/domain/internshipAnnouncement/vo/InternshipAnnouncementStartDate.kt
  src/main/kotlin/com/terning/server/kotlin/domain/internshipAnnouncement/vo/InternshipWorkingPeriod.kt
  src/main/kotlin/com/terning/server/kotlin/ui/api/InternshipAnnouncementController.kt
  src/main/resources/application-test.yml
  src/test/kotlin/com/terning/server/kotlin/application/filter/FilterServiceTest.kt
  src/test/kotlin/com/terning/server/kotlin/application/internshipAnnouncement/InternshipAnnouncementServiceTest.kt
  src/test/kotlin/com/terning/server/kotlin/domain/filter/FilterTest.kt
  src/test/kotlin/com/terning/server/kotlin/domain/internshipAnnouncement/vo/InternshipFilterWorkingPeriodTest.kt
  src/test/kotlin/com/terning/server/kotlin/ui/api/internshipAnnouncemen/InternshipAnnouncementControllerTest.kt
Labels: ✨ feat, 🐋 장순 🐋, size/XL

#103 [✨feat] 필터링 재설정 API 구현
  src/main/kotlin/com/terning/server/kotlin/application/filter/FilterService.kt
  src/main/kotlin/com/terning/server/kotlin/application/filter/dto/FilterRequest.kt
  src/main/kotlin/com/terning/server/kotlin/application/filter/dto/FilterResponse.kt
  src/main/kotlin/com/terning/server/kotlin/domain/filter/Filter.kt
  src/main/kotlin/com/terning/server/kotlin/ui/api/FilterController.kt
  src/test/kotlin/com/terning/server/kotlin/application/filter/FilterServiceTest.kt
  src/test/kotlin/com/terning/server/kotlin/domain/filter/FilterTest.kt
  src/test/kotlin/com/terning/server/kotlin/ui/api/filter/FilterControllerTest.kt
Labels: ✨ feat, 🐬 유빈🐬, size/L

#106 [✨feat] 곧 마감되는 관심 공고
  src/main/kotlin/com/terning/server/kotlin/application/scrap/ScrapService.kt
  src/main/kotlin/com/terning/server/kotlin/application/scrap/dto/UpcomingDeadlineScrapResponse.kt
  src/main/kotlin/com/terning/server/kotlin/domain/scrap/ScrapRepositoryCustom.kt
  src/main/kotlin/com/terning/server/kotlin/domain/scrap/ScrapRepositoryImpl.kt
  src/main/kotlin/com/terning/server/kotlin/domain/user/exception/UserErrorCode.kt
  src/main/kotlin/com/terning/server/kotlin/ui/api/ScrapController.kt
  src/test/kotlin/com/terning/server/kotlin/application/scrap/ScrapServiceTest.kt
  src/test/kotlin/com/terning/server/kotlin/ui/api/scrap/ScrapControllerTest.kt
Labels: ✨ feat, 🐋 장순 🐋, size/L

#109 [✨feat] 공고 상세 정보 API 구현
  src/main/kotlin/com/terning/server/kotlin/application/announcement/AnnouncementService.kt
  src/main/kotlin/com/terning/server/kotlin/application/announcement/dto/DetailAnnouncementResponse.kt
  src/main/kotlin/com/terning/server/kotlin/ui/api/AnnouncementController.kt
  src/test/kotlin/com/terning/server/kotlin/application/announcement/AnnouncementServiceTest.kt
  src/test/kotlin/com/terning/server/kotlin/ui/api/AnnouncementControllerTest.kt
Labels: ✨ feat, 🐬 유빈🐬, size/L

#110 [✨feat] 사용자 필터링 정보 생성 API 구현
  src/main/kotlin/com/terning/server/kotlin/application/filter/FilterService.kt
  src/main/kotlin/com/terning/server/kotlin/application/filter/dto/CreateFilterRequest.kt
  src/main/kotlin/com/terning/server/kotlin/application/filter/dto/GetFilterResponse.kt
  src/main/kotlin/com/terning/server/kotlin/application/filter/dto/UpdateFilterRequest.kt
  src/main/kotlin/com/terning/server/kotlin/ui/api/FilterController.kt
  src/test/kotlin/com/terning/server/kotlin/application/filter/FilterServiceTest.kt
  src/test/kotlin/com/terning/server/kotlin/ui/api/FilterControllerTest.kt
Labels: ✨ feat, 🐬 유빈🐬, size/L

#114 [✨feat] 검색 결과 화면 API 구현
  src/main/kotlin/com/terning/server/kotlin/application/home/HomeService.kt
  src/main/kotlin/com/terning/server/kotlin/application/search/SearchService.kt
  src/main/kotlin/com/terning/server/kotlin/application/search/dto/SearchPageResponse.kt
  src/main/kotlin/com/terning/server/kotlin/domain/internshipAnnouncement/InternshipAnnouncementRepositoryCustom.kt
  src/main/kotlin/com/terning/server/kotlin/domain/internshipAnnouncement/InternshipAnnouncementRepositoryImpl.kt
  src/main/kotlin/com/terning/server/kotlin/ui/api/SearchController.kt
  src/test/kotlin/com/terning/server/kotlin/application/home/HomeServiceTest.kt
  src/test/kotlin/com/terning/server/kotlin/application/search/SearchServiceTest.kt
  src/test/kotlin/com/terning/server/kotlin/ui/api/SearchControllerTest.kt
Labels: ✨ feat, 🐋 장순 🐋, size/XL

#120 [✨feat] 광고 배너 API 구현
  src/main/kotlin/com/terning/server/kotlin/application/search/SearchService.kt
  src/main/kotlin/com/terning/server/kotlin/application/search/dto/BannersView.kt
  src/main/kotlin/com/terning/server/kotlin/ui/api/SearchController.kt
  src/test/kotlin/com/terning/server/kotlin/application/search/SearchServiceTest.kt
  src/test/kotlin/com/terning/server/kotlin/ui/api/SearchControllerTest.kt
Labels: ✨ feat, 🐋 장순 🐋, size/L

#126 [🔀 merge] feat/#119 -> develop (잘못된 머지 해결 및 기능 통합)
  src/main/kotlin/com/terning/server/kotlin/application/search/SearchService.kt
  src/main/kotlin/com/terning/server/kotlin/application/search/dto/BannersView.kt
  src/main/kotlin/com/terning/server/kotlin/application/search/dto/ScrapCountResponse.kt
  src/main/kotlin/com/terning/server/kotlin/domain/internshipAnnouncement/InternshipAnnouncementRepositoryCustom.kt
  src/main/kotlin/com/terning/server/kotlin/domain/internshipAnnouncement/InternshipAnnouncementRepositoryImpl.kt
  src/main/kotlin/com/terning/server/kotlin/domain/internshipAnnouncement/exception/InternshipAnnouncementErrorCode.kt
  src/main/kotlin/com/terning/server/kotlin/ui/api/SearchController.kt
  src/test/kotlin/com/terning/server/kotlin/application/search/SearchServiceTest.kt
  src/test/kotlin/com/terning/server/kotlin/ui/api/SearchControllerTest.kt
Labels: 🔀 merge, 🐋 장순 🐋, size/L

#128 [✨feat] Security구현
  .github/workflows/DEV-CI.yml
  src/main/kotlin/com/terning/server/kotlin/application/auth/AuthService.kt
  src/main/kotlin/com/terning/server/kotlin/application/auth/config/RestTemplateConfig.kt
  src/main/kotlin/com/terning/server/kotlin/application/auth/config/SocialAuthConfig.kt
  src/main/kotlin/com/terning/server/kotlin/application/auth/social/SocialAuthProvider.kt
  src/main/kotlin/com/terning/server/kotlin/application/auth/social/SocialAuthServiceManager.kt
  src/main/kotlin/com/terning/server/kotlin/application/auth/social/apple/AppleAuthProvider.kt
  src/main/kotlin/com/terning/server/kotlin/application/auth/social/apple/AppleAuthTokenValidator.kt
  src/main/kotlin/com/terning/server/kotlin/application/auth/social/apple/ApplePublicKeyClient.kt
  src/main/kotlin/com/terning/server/kotlin/application/auth/social/kakao/KakaoAuthProvider.kt
  src/main/kotlin/com/terning/server/kotlin/application/auth/social/kakao/KakaoAuthTokenValidator.kt
  src/main/kotlin/com/terning/server/kotlin/domain/auth/Auth.kt
  src/main/kotlin/com/terning/server/kotlin/domain/auth/vo/Token.kt
  src/main/kotlin/com/terning/server/kotlin/domain/common/config/ValueConfig.kt
  src/main/kotlin/com/terning/server/kotlin/domain/common/security/jwt/application/JwtClaimsGenerator.kt
  src/main/kotlin/com/terning/server/kotlin/domain/common/security/jwt/application/JwtSigner.kt
  src/main/kotlin/com/terning/server/kotlin/domain/common/security/jwt/application/JwtTokenIssuer.kt
  src/main/kotlin/com/terning/server/kotlin/domain/common/security/jwt/application/JwtTokenManager.kt
  src/main/kotlin/com/terning/server/kotlin/domain/common/security/jwt/auth/AuthenticationTokenFactory.kt
  src/main/kotlin/com/terning/server/kotlin/domain/common/security/jwt/auth/UserAuthentication.kt
  src/main/kotlin/com/terning/server/kotlin/domain/common/security/jwt/exception/JwtErrorCode.kt
  src/main/kotlin/com/terning/server/kotlin/domain/common/security/jwt/provider/JwtKeyProvider.kt
  src/main/kotlin/com/terning/server/kotlin/ui/api/AuthController.kt
  src/main/resources/application-test.yml
  src/test/kotlin/com/terning/server/kotlin/application/auth/AuthServiceTest.kt
  src/test/kotlin/com/terning/server/kotlin/ui/api/AnnouncementControllerTest.kt
  src/test/kotlin/com/terning/server/kotlin/ui/api/AuthControllerTest.kt
  src/test/kotlin/com/terning/server/kotlin/ui/api/CalendarControllerTest.kt
  src/test/kotlin/com/terning/server/kotlin/ui/api/FilterControllerTest.kt
  src/test/kotlin/com/terning/server/kotlin/ui/api/HomeControllerTest.kt
  src/test/kotlin/com/terning/server/kotlin/ui/api/MyPageControllerTest.kt
  src/test/kotlin/com/terning/server/kotlin/ui/api/ScrapControllerTest.kt
  src/test/kotlin/com/terning/server/kotlin/ui/api/SearchControllerTest.kt
Labels: ✨ feat, 🐬 유빈🐬, size/XL

#127 [✨feat] 소셜 로그인 API 구현
  .github/workflows/DEV-CI.yml
  build.gradle.kts
  src/main/kotlin/com/terning/server/kotlin/application/auth/AuthService.kt
  src/main/kotlin/com/terning/server/kotlin/application/auth/config/RestTemplateConfig.kt
  src/main/kotlin/com/terning/server/kotlin/application/auth/config/SocialAuthConfig.kt
  src/main/kotlin/com/terning/server/kotlin/application/auth/dto/SignInRequest.kt
  src/main/kotlin/com/terning/server/kotlin/application/auth/dto/SignInResponse.kt
  src/main/kotlin/com/terning/server/kotlin/application/auth/social/SocialAuthProvider.kt
  src/main/kotlin/com/terning/server/kotlin/application/auth/social/SocialAuthServiceManager.kt
  src/main/kotlin/com/terning/server/kotlin/application/auth/social/apple/AppleAuthProvider.kt
  src/main/kotlin/com/terning/server/kotlin/application/auth/social/apple/AppleAuthTokenValidator.kt
  src/main/kotlin/com/terning/server/kotlin/application/auth/social/apple/ApplePublicKeyClient.kt
  src/main/kotlin/com/terning/server/kotlin/application/auth/social/kakao/KakaoAuthProvider.kt
  src/main/kotlin/com/terning/server/kotlin/application/auth/social/kakao/KakaoAuthTokenValidator.kt
  src/main/kotlin/com/terning/server/kotlin/application/mypage/MyPageService.kt
  src/main/kotlin/com/terning/server/kotlin/application/mypage/ProfileRequest.kt
  src/main/kotlin/com/terning/server/kotlin/application/mypage/ProfileResponse.kt
  src/main/kotlin/com/terning/server/kotlin/domain/auth/Auth.kt
  src/main/kotlin/com/terning/server/kotlin/domain/auth/AuthRepository.kt
  src/main/kotlin/com/terning/server/kotlin/domain/auth/exception/AuthErrorCode.kt
  src/main/kotlin/com/terning/server/kotlin/domain/auth/vo/AuthId.kt
  src/main/kotlin/com/terning/server/kotlin/domain/auth/vo/AuthType.kt
  src/main/kotlin/com/terning/server/kotlin/domain/auth/vo/RefreshToken.kt
  src/main/kotlin/com/terning/server/kotlin/domain/auth/vo/Token.kt
  src/main/kotlin/com/terning/server/kotlin/domain/common/config/ValueConfig.kt
  src/main/kotlin/com/terning/server/kotlin/domain/common/security/jwt/application/JwtClaimsGenerator.kt
  src/main/kotlin/com/terning/server/kotlin/domain/common/security/jwt/application/JwtSigner.kt
  src/main/kotlin/com/terning/server/kotlin/domain/common/security/jwt/application/JwtTokenIssuer.kt
  src/main/kotlin/com/terning/server/kotlin/domain/common/security/jwt/application/JwtTokenManager.kt
  src/main/kotlin/com/terning/server/kotlin/domain/common/security/jwt/auth/AuthenticationTokenFactory.kt
  src/main/kotlin/com/terning/server/kotlin/domain/common/security/jwt/auth/UserAuthentication.kt
  src/main/kotlin/com/terning/server/kotlin/domain/common/security/jwt/exception/JwtErrorCode.kt
  src/main/kotlin/com/terning/server/kotlin/domain/common/security/jwt/provider/JwtKeyProvider.kt
  src/main/kotlin/com/terning/server/kotlin/ui/api/AuthController.kt
  src/main/kotlin/com/terning/server/kotlin/ui/api/MyPageController.kt
  src/main/resources/application-test.yml
  src/test/kotlin/com/terning/server/kotlin/application/auth/AuthServiceTest.kt
  src/test/kotlin/com/terning/server/kotlin/application/mypage/MyPageServiceTest.kt
  src/test/kotlin/com/terning/server/kotlin/config/TestSecurityConfig.kt
  src/test/kotlin/com/terning/server/kotlin/ui/api/AnnouncementControllerTest.kt
  src/test/kotlin/com/terning/server/kotlin/ui/api/AuthControllerTest.kt
  src/test/kotlin/com/terning/server/kotlin/ui/api/CalendarControllerTest.kt
  src/test/kotlin/com/terning/server/kotlin/ui/api/FilterControllerTest.kt
  src/test/kotlin/com/terning/server/kotlin/ui/api/HomeControllerTest.kt
  src/test/kotlin/com/terning/server/kotlin/ui/api/MyPageControllerTest.kt
  src/test/kotlin/com/terning/server/kotlin/ui/api/ScrapControllerTest.kt
  src/test/kotlin/com/terning/server/kotlin/ui/api/SearchControllerTest.kt
Labels: ✨ feat, 🐬 유빈🐬, size/XL

#130 [✨feat] 회원가입 API 구현
  src/main/kotlin/com/terning/server/kotlin/application/auth/AuthService.kt
  src/main/kotlin/com/terning/server/kotlin/application/auth/dto/SignInResponse.kt
  src/main/kotlin/com/terning/server/kotlin/application/auth/dto/SignUpRequest.kt
  src/main/kotlin/com/terning/server/kotlin/application/auth/dto/SignUpResponse.kt
  src/main/kotlin/com/terning/server/kotlin/ui/api/AuthController.kt
  src/test/kotlin/com/terning/server/kotlin/application/auth/AuthServiceTest.kt
  src/test/kotlin/com/terning/server/kotlin/ui/api/AuthControllerTest.kt
Labels: ✨ feat, 🐬 유빈🐬, size/L

#135 [✨feat] 계정 탈퇴 API 구현
  src/main/kotlin/com/terning/server/kotlin/application/auth/AuthService.kt
  src/main/kotlin/com/terning/server/kotlin/domain/user/User.kt
  src/main/kotlin/com/terning/server/kotlin/ui/api/AuthController.kt
  src/test/kotlin/com/terning/server/kotlin/application/auth/AuthServiceTest.kt
  src/test/kotlin/com/terning/server/kotlin/ui/api/AuthControllerTest.kt
Labels: ✨ feat, 🐬 유빈🐬, size/M

#136 [✨feat] 토큰 재발급 API 구현
  src/main/kotlin/com/terning/server/kotlin/application/auth/AuthService.kt
  src/main/kotlin/com/terning/server/kotlin/application/auth/dto/TokenReissueResponse.kt
  src/main/kotlin/com/terning/server/kotlin/domain/auth/AuthRepository.kt
  src/main/kotlin/com/terning/server/kotlin/domain/auth/vo/Token.kt
  src/main/kotlin/com/terning/server/kotlin/domain/common/security/jwt/application/JwtTokenManager.kt
  src/main/kotlin/com/terning/server/kotlin/domain/common/security/jwt/auth/AuthenticationTokenFactory.kt
  src/main/kotlin/com/terning/server/kotlin/ui/api/AuthController.kt
  src/test/kotlin/com/terning/server/kotlin/application/auth/AuthServiceTest.kt
  src/test/kotlin/com/terning/server/kotlin/ui/api/AuthControllerTest.kt
Labels: ✨ feat, 🐬 유빈🐬, size/L

#139 [♻️ refactor] 컨트롤러에 @AuthenticationPrincipal을 사용하여 인증된 사용자 ID 연동
  .github/workflows/DEV-CI.yml
  src/main/kotlin/com/terning/server/kotlin/ui/api/AnnouncementController.kt
  src/main/kotlin/com/terning/server/kotlin/ui/api/CalendarController.kt
  src/main/kotlin/com/terning/server/kotlin/ui/api/FilterController.kt
  src/main/kotlin/com/terning/server/kotlin/ui/api/HomeController.kt
  src/main/kotlin/com/terning/server/kotlin/ui/api/MyPageController.kt
  src/main/kotlin/com/terning/server/kotlin/ui/api/ScrapController.kt
  src/main/kotlin/com/terning/server/kotlin/ui/api/SearchController.kt
  src/main/kotlin/com/terning/server/kotlin/utils/temp
  src/main/resources/application-local.yml
  src/test/kotlin/com/terning/server/kotlin/application/auth/AuthServiceTest.kt
  src/test/kotlin/com/terning/server/kotlin/support/WithMockCustomUser.kt
  src/test/kotlin/com/terning/server/kotlin/support/WithMockCustomUserSecurityContextFactory.kt
  src/test/kotlin/com/terning/server/kotlin/ui/api/AnnouncementControllerTest.kt
  src/test/kotlin/com/terning/server/kotlin/ui/api/AuthControllerTest.kt
  src/test/kotlin/com/terning/server/kotlin/ui/api/CalendarControllerTest.kt
  src/test/kotlin/com/terning/server/kotlin/ui/api/FilterControllerTest.kt
  src/test/kotlin/com/terning/server/kotlin/ui/api/HomeControllerTest.kt
  src/test/kotlin/com/terning/server/kotlin/ui/api/MyPageControllerTest.kt
  src/test/kotlin/com/terning/server/kotlin/ui/api/ScrapControllerTest.kt
  src/test/kotlin/com/terning/server/kotlin/ui/api/SearchControllerTest.kt
Labels: ♻️ refactor, 🐋 장순 🐋, size/L

#143 [🔀merge] develop -> staging 변경사항 반영
  .github/workflows/DEV-CI.yml
Labels: 🔀 merge, 🐬 유빈🐬, size/S

#146 [🔀merge] staging -> develop 변경사항 반영
  .github/workflows/DOCKER-CD-STAGING.yml
  Dockerfile-staging
Labels: size/M

#148 chore(docker) : modify docker file naming
  .github/workflows/DOCKER-CD-STAGING.yml
Labels: size/XS

#149 merge(docker) : modify docker file naming
  .github/workflows/DOCKER-CD-STAGING.yml
Labels: size/XS

#151 merge(docker) : GraalVM 공식 빌더 이미지 사용
  Dockerfile-staging
Labels: size/XS

#152 chore(docker): GraalVM 네이티브 빌드 Dockerfile 최종 수정
  Dockerfile-staging
Labels: size/M

#153 chore(docker): GraalVM 네이티브 빌드 Dockerfile 최종 수정
  Dockerfile-staging
Labels: size/M
