Repository teamterning/Terning-Server-Kotlin, pull requests merged in 2025-05, with the labels that each got.

#13 [✨feat] ktlint 설치
  .github/workflows/DEV-CI.yml
  build.gradle.kts
  src/main/kotlin/com/terning/server/kotlin/ui/api/ApiResponse.kt
  src/main/kotlin/com/terning/server/kotlin/ui/api/ExceptionHandler.kt
  src/test/kotlin/com/terning/server/kotlin/ServerKotlinApplicationTests.kt
Labels: ✨ feat, 🐬 유빈🐬, size/M

#15 [📦 chore] GraalVM JDK 및 native-image 빌드 환경 적용
  .github/workflows/DEV-CI.yml
Labels: 📦 chore, 🐋 장순 🐋, size/S

#16 [✨feat] 사용자 도메인 에러 코드 및 커스텀 예외 클래스 구현
  src/main/kotlin/com/terning/server/kotlin/domain/temp
  src/main/kotlin/com/terning/server/kotlin/domain/user/UserErrorCode.kt
  src/main/kotlin/com/terning/server/kotlin/domain/user/UserException.kt
  src/main/kotlin/com/terning/server/kotlin/ui/api/ExceptionHandler.kt
Labels: ✨ feat, 🐋 장순 🐋, size/S

#19 [✨feat] User 도메인 구현
  src/main/kotlin/com/terning/server/kotlin/domain/common/BaseRootEntity.kt
  src/main/kotlin/com/terning/server/kotlin/domain/user/ProfileImage.kt
  src/main/kotlin/com/terning/server/kotlin/domain/user/User.kt
  src/main/kotlin/com/terning/server/kotlin/domain/user/UserName.kt
  src/main/kotlin/com/terning/server/kotlin/domain/user/UserState.kt
  src/test/kotlin/com/terning/server/kotlin/domain/user/ProfileImageTest.kt
  src/test/kotlin/com/terning/server/kotlin/domain/user/UserNameTest.kt
  src/test/kotlin/com/terning/server/kotlin/domain/user/UserTest.kt
Labels: ✨ feat, 🐬 유빈🐬, size/L

#21 [✨feat] Color(Scrap) 구현
  src/main/kotlin/com/terning/server/kotlin/domain/scrap/Color.kt
  src/main/kotlin/com/terning/server/kotlin/domain/scrap/ScrapErrorCode.kt
  src/main/kotlin/com/terning/server/kotlin/domain/scrap/ScrapException.kt
  src/main/kotlin/com/terning/server/kotlin/ui/api/ExceptionHandler.kt
  src/test/kotlin/com/terning/server/kotlin/domain/scrap/ColorTest.kt
Labels: ✨ feat, 🐋 장순 🐋, size/M

#25 [✨feat] Scrap(Filter) 구현
  src/main/kotlin/com/terning/server/kotlin/domain/scrap/Scrap.kt
Labels: ✨ feat, 🐋 장순 🐋, size/M

#27 [✨feat] WorkingPeriod(Filter) 구현
  src/main/kotlin/com/terning/server/kotlin/domain/filter/FilterErrorCode.kt
  src/main/kotlin/com/terning/server/kotlin/domain/filter/FilterException.kt
  src/main/kotlin/com/terning/server/kotlin/domain/filter/WorkingPeriod.kt
  src/test/kotlin/com/terning/server/kotlin/domain/filter/WorkingPeriodTest.kt
Labels: ✨ feat, 🐋 장순 🐋, size/M

#29 [✨feat] JobType(Filter) 구현
  src/main/kotlin/com/terning/server/kotlin/domain/filter/JobType.kt
  src/main/kotlin/com/terning/server/kotlin/domain/scrap/ScrapErrorCode.kt
  src/test/kotlin/com/terning/server/kotlin/domain/filter/JobTypeTest.kt
Labels: ✨ feat, 🐋 장순 🐋, size/M

#31 [✨feat] Grade(Filter) 구현
  src/main/kotlin/com/terning/server/kotlin/domain/filter/FilterErrorCode.kt
  src/main/kotlin/com/terning/server/kotlin/domain/filter/Grade.kt
  src/test/kotlin/com/terning/server/kotlin/domain/filter/GradeTest.kt
Labels: ✨ feat, 🐋 장순 🐋, size/M

#35 [✨feat] Filter 구현
  src/main/kotlin/com/terning/server/kotlin/domain/filter/Filter.kt
  src/main/kotlin/com/terning/server/kotlin/domain/filter/Month.kt
  src/main/kotlin/com/terning/server/kotlin/domain/filter/StartDate.kt
  src/main/kotlin/com/terning/server/kotlin/domain/filter/Year.kt
  src/test/kotlin/com/terning/server/kotlin/domain/filter/FilterTest.kt
  src/test/kotlin/com/terning/server/kotlin/domain/filter/GradeTest.kt
  src/test/kotlin/com/terning/server/kotlin/domain/filter/JobTypeTest.kt
  src/test/kotlin/com/terning/server/kotlin/domain/filter/MonthTest.kt
  src/test/kotlin/com/terning/server/kotlin/domain/filter/StartDateTest.kt
  src/test/kotlin/com/terning/server/kotlin/domain/filter/WorkingPeriodTest.kt
  src/test/kotlin/com/terning/server/kotlin/domain/filter/YearTest.kt
  src/test/kotlin/com/terning/server/kotlin/domain/scrap/ColorTest.kt
Labels: ✨ feat, 🐋 장순 🐋, size/L

#39 [✨feat] AuthType 구현
  src/main/kotlin/com/terning/server/kotlin/domain/auth/AuthErrorCode.kt
  src/main/kotlin/com/terning/server/kotlin/domain/auth/AuthException.kt
  src/main/kotlin/com/terning/server/kotlin/domain/auth/AuthType.kt
  src/main/kotlin/com/terning/server/kotlin/ui/api/ExceptionHandler.kt
  src/test/kotlin/com/terning/server/kotlin/domain/auth/AuthTypeTest.kt
Labels: ✨ feat, 🐬 유빈🐬, size/M

#40 [✨feat] Auth 구현
  src/main/kotlin/com/terning/server/kotlin/domain/auth/Auth.kt
  src/main/kotlin/com/terning/server/kotlin/domain/auth/AuthErrorCode.kt
  src/main/kotlin/com/terning/server/kotlin/domain/auth/AuthId.kt
  src/main/kotlin/com/terning/server/kotlin/domain/auth/RefreshToken.kt
Labels: ✨ feat, 🐬 유빈🐬, size/M

#41 [✨feat] Banner 구현
  src/main/kotlin/com/terning/server/kotlin/domain/banner/Banner.kt
  src/main/kotlin/com/terning/server/kotlin/domain/banner/ImageUrl.kt
  src/main/kotlin/com/terning/server/kotlin/domain/banner/Link.kt
Labels: ✨ feat, 🐬 유빈🐬, size/M

#72 [📦chore] GraalVM 액션 안정화를 위한 CI 설정 개선
  .github/workflows/DEV-CI.yml
Labels: 📦 chore, 🐋 장순 🐋, size/XS

#49 [✨feat] InternshipAnnouncement 커스텀 예외 적용
  src/main/kotlin/com/terning/server/kotlin/domain/internshipAnnouncement/Deadline.kt
  src/main/kotlin/com/terning/server/kotlin/domain/internshipAnnouncement/InternshipErrorCode.kt
  src/main/kotlin/com/terning/server/kotlin/domain/internshipAnnouncement/InternshipException.kt
  src/main/kotlin/com/terning/server/kotlin/domain/internshipAnnouncement/ScrapCount.kt
  src/main/kotlin/com/terning/server/kotlin/domain/internshipAnnouncement/ViewCount.kt
  src/test/kotlin/com/terning/server/kotlin/domain/internshipAnnouncement/DeadlineTest.kt
  src/test/kotlin/com/terning/server/kotlin/domain/internshipAnnouncement/ScrapCountTest.kt
Labels: ✨ feat, 🐋 장순 🐋, size/M

#57 [✨feat] InternshipWorkingPeriod 구현
  src/main/kotlin/com/terning/server/kotlin/domain/internshipAnnouncement/InternshipErrorCode.kt
  src/main/kotlin/com/terning/server/kotlin/domain/internshipAnnouncement/InternshipWorkingPeriod.kt
  src/test/kotlin/com/terning/server/kotlin/domain/internshipAnnouncement/InternshipWorkingPeriodTest.kt
Labels: ✨ feat, 🐋 장순 🐋, size/M

#59 [✨feat] StartDate(InternshipAnnouncement) 구현
  src/main/kotlin/com/terning/server/kotlin/domain/internshipAnnouncement/InternshipAnnouncementMonth.kt
  src/main/kotlin/com/terning/server/kotlin/domain/internshipAnnouncement/InternshipAnnouncementStartDate.kt
  src/main/kotlin/com/terning/server/kotlin/domain/internshipAnnouncement/InternshipAnnouncementYear.kt
  src/main/kotlin/com/terning/server/kotlin/domain/internshipAnnouncement/InternshipErrorCode.kt
  src/test/kotlin/com/terning/server/kotlin/domain/internshipAnnouncement/InternshipAnnouncementMonthTest.kt
  src/test/kotlin/com/terning/server/kotlin/domain/internshipAnnouncement/InternshipAnnouncementStartDateTest.kt
  src/test/kotlin/com/terning/server/kotlin/domain/internshipAnnouncement/InternshipAnnouncementYearTest.kt
Labels: ✨ feat, 🐋 장순 🐋, size/L

#61 [✨feat] CompanyImageUrl VO 구현
  src/main/kotlin/com/terning/server/kotlin/domain/internshipAnnouncement/CompanyLogoUrl.kt
  src/main/kotlin/com/terning/server/kotlin/domain/internshipAnnouncement/InternshipErrorCode.kt
  src/test/kotlin/com/terning/server/kotlin/domain/internshipAnnouncement/CompanyLogoUrlTest.kt
Labels: ✨ feat, 🐋 장순 🐋, size/M

#63 [✨feat] InternshipAnnouncementUrl VO 구현
  src/main/kotlin/com/terning/server/kotlin/domain/internshipAnnouncement/InternshipAnnouncementUrl.kt
  src/main/kotlin/com/terning/server/kotlin/domain/internshipAnnouncement/InternshipErrorCode.kt
  src/test/kotlin/com/terning/server/kotlin/domain/internshipAnnouncement/InternshipAnnouncementUrlTest.kt
Labels: ✨ feat, 🐋 장순 🐋, size/M

#69 [📦chore] ktlint 규칙 수정
  .editorconfig
  src/main/kotlin/com/terning/server/kotlin/domain/user/User.kt
Labels: 📦 chore, 🐬 유빈🐬, size/XS
